version: '3.9'

services:
  template:
    image: docker
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest #The recommended is to use a specific version
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin13
      POSTGRES_DB: template
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    name: backend_network
    driver: bridge

volumes:
  postgres_data: {}