version: '3.9'

services:
  template:
    image: docker
    shm_size: 128mb #Shared memory
    deploy:
      resources:
        limits: #Max memory usage
          cpus: '0.5' #Limits how much percent will be used, in this example is 7%
          memory: 512M #Limits to use 256MB
        reservations:
          cpus: '0.25' #Minium for the service work!
          memory: 256M #Minium for the service work!
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest #The recommended is to use a specific version
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: template
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M #In this example you won't even use 10%, but it's a good parameter to start!
        reservations:
          cpus: '0.1'
          memory: 256M
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    name: backend_network
    driver: bridge

volumes:
  postgres_data: {}